dockerfile: Dockerfile

build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:latest
  amd64: ghcr.io/home-assistant/amd64-base-python:latest
  armv7: ghcr.io/home-assistant/armv7-base-python:latest
