name: Cloudflare Private DDNS Updater
description: Cloudflare Private DDNS Updater
version: 1.0.25
slug: cloudflare_private_ddns_updater
init: false
host_network: true
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
startup: services
options:
  config: []
schema:
  config:
  - zone: str
    token: str
    domains: str
