name: "DDNS Updater"
description: "DDNS Updater"
version: "1.0.9"
slug: "cloudflare_private_ddns_updater"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services

options:
  interface: enp6s18
  config: []

schema:
  interface: str
  config:
    - zone: str
      token: str
      domains: str
