name: "DDNS Updater"
description: "DDNS Updater"
version: "1.0.9"
slug: "ddns_updater"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services

options:
  config: /etc/ddclient/ddclient.conf
schema:
  config: str
